### PR TITLE
GitHub actions to release packages and check for errors

### PR DESCRIPTION
**Pull request by alt-art**

### CODE REVIEW

**Comment by alt-art** [comment]
The GitHub actions are a try-and-fix thing; you can't test them on a local machine and must change them based on the logs. Let me know if something is incorrect so I can fix the errors.

You must add the crates.io token to the repository to publish with the action. The SECRET name is `CRATES_IO_TOKEN`. I will link a post showing how to add this secret to a repository.

**Comment by alt-art** [comment]
Closes #3

**Comment by newtoallofthis123** [comment]
That's so kind of you @alt-art. Will do that at the latest

**Comment by alt-art** [comment]
https://pratikpc.medium.com/publishing-crates-using-github-actions-165ee67780e1

**Comment by alt-art** [comment]
I think now I have fixed everything

**Comment by newtoallofthis123** [comment]
Yep....I'll start doing my stuff on my end now 😅

**Pull request merged**
